fixtures:
  repositories:
    concat:
      repo: 'https://github.com/puppetlabs/puppetlabs-concat'
      branch: '2.1.x'
    stdlib:      'https://github.com/puppetlabs/puppetlabs-stdlib.git'

  symlinks:
    dhcp: "#{source_dir}"
